name: fraud_detection_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - shap
  - lime
  - pyyaml
  - pip
  - pip:
      - transformers==4.30.0
      - torch