data:
  data_path: "../data/credit_card_behaviour_score.csv.gz"
  test_size: 0.2
  random_state: 42

model:
  type: "RandomForest"
  parameters:
    n_estimators: 100
    max_depth: 8

explainability:
  traditional_methods:
    - LIME
    - SHAP
    - PDP
    - ALE
    - IntegratedGradients
    - Counterfactual
  